### PR TITLE
Rename Support Steward to Triager

### PR DESCRIPTION
**Pull request by sgibson91**
Todo:

- [x] Update name of Geekbot standup
- [x] Update name of team in Slack
- [ ] Might also need to update the existing calendar entries as well as I believe they filter on role name
  - Addressed by https://github.com/2i2c-org/team-roles-geekbot-sweep/pull/200/commits/5d3b2c88e3abd641ef9569c88bdeadd4ee6dc7a8

### CODE REVIEW

**Review by damianavila — APPROVED** [review]
Lovely!

**Comment by damianavila** [comment]
@sgibson91, are you taking care (can you :wink:) of the remaining items in the todo list as well?

**Comment by sgibson91** [comment]
@damianavila yep can do!

**Comment by sgibson91** [comment]
> * Might also need to update the existing calendar entries as well as I believe they filter on role name

I pushed [`5d3b2c8` (#200)](https://github.com/2i2c-org/team-roles-geekbot-sweep/pull/200/commits/5d3b2c88e3abd641ef9569c88bdeadd4ee6dc7a8) which hopefully means we won't have to worry about this item

**Pull request merged**
